name: Docker

on: workflow_dispatch
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Build
        run: docker build -t ghcr.io/at8eqeq3/mytexlive .
      - name: Publish
        run: docker push ghcr.io/at8eqeq3/mytexlive:latest