name: Ruby

on:
  push:
    branches: [ master ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        uses: ./
      - name: Publish PDF
        uses: actions/upload-artifact@v3
        with:
          name: altermann.pdf
          path: altermann.pdf